#!/usr/bin/env python3
"""
Consolidated News Analysis Module
=================================
Combines functionality from news_analysis.py and news_source_classification.py
to provide a unified interface for news source classification and analysis.
"""

import json
import os
from pathlib import Path
import pandas as pd
import polars as pl
from datetime import datetime
import re
from urllib.parse import urlparse
from typing import List, Dict, Any, Tuple, Optional
from collections import Counter

# =============================================================================
# NEWS SOURCE CLASSIFICATION DATA
# =============================================================================

# Alternative news sources (comprehensive list)
alternative_news_sources = [
    "180grader.dk",
    "24nyt.dk",
    "arbejderen.dk",
    "denkorteavis.dk",
    "dkdox.tv",
    "document.dk",
    "folkets.dk",
    "frihedensstemme.dk",
    "indblik.dk",
    "konfront.dk",
    "kontrast.dk",
    "newspeek.info",
    "nordfront.dk",
    "piopio.dk",
    "redox.dk",
    "sameksistens.com",
    "solidaritet.dk",
    "psst-nyt.dk",
    "dagensblaeser.net",
    "danmarksfriefjernsyn.dk",
    "denuafhaengige.dk",
    "freeobserver.org",
    "tv.frihedensstemme.dk",
    "frihedsbrevet.dk",
    "indblik.net",
    "responsmedie.dk",
    # Swedish alternative sources
    "aktuelltfokus.se",
    "arbetaren.se",
    "bubb.la",
    "bulletin.nu",
    "detgodasamhallet.com",
    "direktaktion.nu",
    "epochtimes.se",
    "exakt24.se",
    "feministisktperspektiv.se",
    "flamman.se",
    "folkungen.se",
    "friasidor.is",
    "friatider.se",
    "ledarsidorna.se",
    "nationalisten.se",
    "newsvoice.se",
    "nordfront.se",
    "nyadagbladet.se",
    "nyatider.nu",
    "nyheteridag.se",
    "nyhetsbyran.org",
    "proletaren.se",
    "svegot.se",
    "riks.se",
    "samnytt.se",
    "samtiden.nu",
    "tidningensyre.se",
    "vaken.se",
    # Austrian alternative sources
    "addendum.org",
    "allesroger.at",
    "alpenschau.com",
    "anschlaege.at",
    "auf1.tv",
    "contra-magazin.com",
    "info-direkt.eu",
    "kontrast.at",
    "moment.at",
    "mosaik-blog.at",
    "neuezeit.at",
    "report24.news",
    "tagesstimme.com",
    "unser-mitteleuropa.com",
    "unsere-zeitung.at",
    "unzensuriert.at",
    "volksstimme.at",
    "wochenblick.at",
    "zackzack.at",
    "zurzeit.at",
    # German alternative sources
    "achgut.com",
    "afd-kompakt.de",
    "allgemeine-zeitung.de",
    "alternative-presse.de",
    "antifaschistische-nachrichten.de",
    "apotheken-umschau.de",
    "arbeiterfotografie.com",
    "arbeiterstimme.de",
    "augsburger-allgemeine.de",
    "autorenwelt.de",
    "baden-wuerttemberg.de",
    "badische-zeitung.de",
    "bayernkurier.de",
    "bbv-net.de",
    "boehme-zeitung.de",
    "borkenerzeitung.de",
    "boersen-zeitung.de",
    "mainpost.de",
    "main-echo.de",
    "maz-online.de",
    "braunschweiger-zeitung.de",
    "brv-zeitung.de",
    "boyens-medien.de",
    "allgaeuer-zeitung.de",
    "buerstaedter-zeitung.de",
    "butzbacher-zeitung.de",
    "staatsanzeiger.de",
    "cellesche-zeitung.de",
    "ovb-online.de",
    "evangelisch.de",
    "zeit.de",
    "cnv-medien.de",
    "merkur.de",
    "echo-online.de",
    "das-parlament.de",
    "24vest.de",
    "dewezet.de",
    "n-land.de",
    "freitag.de",
    "prignitzer.de",
    "tagesspiegel.de",
    "teckbote.de",
    "westallgaeuer-zeitung.de",
    "deutsche-handwerks-zeitung.de",
    "dvz.de",
    "die-glocke.de",
    "dieharke.de",
    "nq-online.de",
    "rheinpfalz.de",
    "die-tagespost.de",
    "welt.de",
    "da-imnetz.de",
    "mittelhessen.de",
    "lvz.de",
    "saechsische.de",
    "donaukurier.de",
    "dorstenerzeitung.de",
    "dnn.de",
    "dzonline.de",
    "gea.de",
    "kn-online.de",
    "goettinger-tageblatt.de",
    "einbecker-morgenpost.de",
    "ejz.de",
    "emderzeitung.de",
    "ev-online.de",
    "esslinger-zeitung.de",
    "express.de",
    "fehmarn24.de",
    "fla.de",
    "verlag-dreisbach.de",
    "hna.de",
    "wlz-online.de",
    "frankenpost.de",
    "faz.net",
    "fr.de",
    "flz.de",
    "fnweb.de",
    "freiepresse.de",
    "fuldaerzeitung.de",
    "gandersheimer-kreisblatt.de",
    "gaeubote.de",
    "gnz.de",
    "kreis-anzeiger.de",
    "general-anzeiger-bonn.de",
    "ga-online.de",
    "giessener-anzeiger.de",
    "gifhorner-rundschau.de",
    "gmuender-tagespost.de",
    "goslarsche.de",
    "gn-online.de",
    "muensterschezeitung.de",
    "haller-kreisblatt.de",
    "halternerzeitung.de",
    "abendblatt.de",
    "mopo.de",
    "hanauer.de",
    "handelsblatt.com",
    "haz.de",
    "harzkurier.de",
    "stimme.de",
    "hellwegeranzeiger.de",
    "helmstedter-nachrichten.de",
    "hersfelder-zeitung.de",
    "hildesheimer-allgemeine.de",
    "hurriyet.com.tr",
    "ivz-aktuell.de",
    "ikz-online.de",
    "juedische-allgemeine.de",
    "kevelaerer-blatt.de",
    "ksta.de",
    "kornwestheimer-zeitung.de",
    "krzbb.de",
    "lahrer-zeitung.de",
]

# Mainstream news sources (comprehensive list)
mainstream_news_sources = [
    # Danish National Media
    "dr.dk",
    "tv2.dk",
    "politiken.dk",
    "berlingske.dk",
    "information.dk",
    "jyllands-posten.dk",
    "borsen.dk",
    "ekstrabladet.dk",
    "bt.dk",
    "kristeligt-dagblad.dk",
    "weekendavisen.dk",
    "finans.dk",
    "altinget.dk",
    "tv2ostjylland.dk",
    "dbrs.dk",
    "samsoposten.dk",
    "mediawatch.dk",
    "lokalnytkolding.dk",
    "hvidovreavis.dk",
    "sydmedier.dk",
    "folkebladetlemvig.dk",
    "nyborgavis.dk",
    "lokalnythjoerring.dk",
    "nordhavn-avis.dk",
    "lokalnytaalborg.dk",
    "midtvendsysselavis.dk",
    "Østvendsysselfolkeblad.dk",
    "lokalnytassens.dk",
    "koldingavisen.dk",
    "pingvinnyt.dk",
    "naernyt.dk",
    "fla.de",
    "hverdagsnyt.dk",
    "oestbirk-avis.dk",
    "hornsherredlokalavis.dk",
    "voreslokalavis.dk",
    "medtechnews.dk",
    "hjertingposten.dk",
    "nyheder.dk",
    "saebyavis.dk",
    "valavis.blogspot.com",
    "lyngposten.com",
    "aeroedagblad.dk",
    "vafo.dk",
    "kanalfrederikshavn.dk",
    "fodevarewatch.dk",
    "nb-okonomi.dk",
    "tv2kosmopol.dk",
    "ugebrev.dk",
    "lokalnytkoebenhavn.dk",
    "skivefolkeblad.dk",
    "lokalnytodense.dk",
    "vodskovavis.dk",
    "farsoeavis.dk",
    "frederiksbergliv.dk",
    "videnskab.dk",
    "dragoer-nyt.dk",
    "jyllandsavisen.dk",
    "tvmidtvest.dk",
    "a4medier.dk",
    "midtjyllandsavis.dk",
    "viborg-folkeblad.dk",
    "ib.dk",
    "lokalnytfredericia.dk",
    "skanderborg.lokalavisen.dk",
    "landbrugsavisen.dk",
    "lokalnytnyborg.dk",
    "folkebladet.info",
    "orestad-avis.dk",
    "netavisnord.dk",
    "standby.dk",
    "erhvervplus.dk",
    "olfi.dk",
    "zetland.dk",
    "kunmors.dk",
    "tvsyd.dk",
    "odenseavisen.dk",
    "radar.dk",
    "nibeavis.dk",
    "tv2bornholm.dk",
    "pov.international",
    "skanderborgliv.dk",
    "fanougeblad.dk",
    "herpaaoeen.dk",
    "lokalavisen.dk",
    "mm.dk",
    "journalista.dk",
    "norddjurs.lokalavisen.dk",
    "fjordavisen.nu",
    "pro.ing.dk",
    # Danish Online-Only News
    "mediawatch.dk",
    "journalisten.dk",
    "mm.dk",
    "ing.dk",
    "version2.dk",
    # International Mainstream Sources
    "bbc.com",
    "bbc.co.uk",
    "nytimes.com",
    "theguardian.com",
    "reuters.com",
    "cnn.com",
    "washingtonpost.com",
    "bloomberg.com",
    "economist.com",
    "BBC",
    "CNN",
    "Reuters",
    # German Mainstream Sources
    "aachener-nachrichten.de",
    "aachener-zeitung.de",
    "schwaebische.de",
    "wiesbadener-kurier.de",
    "bo.de",
    "bnn.de",
    "kreiszeitung.de",
    "weser-kurier.de",
    "wn.de",
    "augsburger-allgemeine.de",
    "aichacher-zeitung.de",
    "swp.de",
    "alfelder-zeitung.de",
    "waz-online.de",
    "allgaeuer-anzeigeblatt.de",
    "idowa.de",
    "azonline.de",
    "allgemeine-zeitung.de",
    "come-on.de",
    "giessener-allgemeine.de",
    "pnp.de",
    "az-online.de",
    "nordbayern.de",
    "mittelbayerische.de",
    "onetz.de",
    "nordkurier.de",
    "derpatriot.de",
    "harlinger.de",
    "svz.de",
    "aerztezeitung.de",
    "bz-berlin.de",
    "bkz.de",
    "nw.de",
    "westfalen-blatt.de",
    "rnz.de",
    "fnp.de",
    "badische-zeitung.de",
    "badisches-tagblatt.de",
    "shz.de",
    "infranken.de",
    "bayerische-staatszeitung.de",
    "bayernkurier.de",
    "berchtesgadener-anzeiger.de",
    "rundschau-online.de",
    "rp-online.de",
    "rhoenundsaalepost.de",
    "ostsee-zeitung.de",
    "morgenweb.de",
    "abendblatt-berlin.de",
    "berliner-kurier.de",
    "morgenpost.de",
    "berliner-zeitung.de",
    "noz.de",
    "bild.de",
    "szbz.de",
    "bbv-net.de",
    "boehme-zeitung.de",
    "borkenerzeitung.de",
    "boersen-zeitung.de",
    "mainpost.de",
    "main-echo.de",
    "maz-online.de",
    "braunschweiger-zeitung.de",
    "brv-zeitung.de",
    "boyens-medien.de",
    "allgaeuer-zeitung.de",
    "buerstaedter-zeitung.de",
    "butzbacher-zeitung.de",
    "staatsanzeiger.de",
    "cellesche-zeitung.de",
    "ovb-online.de",
    "evangelisch.de",
    "zeit.de",
    "cnv-medien.de",
    "merkur.de",
    "echo-online.de",
    "das-parlament.de",
    "24vest.de",
    "dewezet.de",
    "n-land.de",
    "freitag.de",
    "prignitzer.de",
    "tagesspiegel.de",
    "teckbote.de",
    "westallgaeuer-zeitung.de",
    "deutsche-handwerks-zeitung.de",
    "dvz.de",
    "die-glocke.de",
    "dieharke.de",
    "nq-online.de",
    "rheinpfalz.de",
    "die-tagespost.de",
    "welt.de",
    "da-imnetz.de",
    "mittelhessen.de",
    "lvz.de",
    "saechsische.de",
    "donaukurier.de",
    "dorstenerzeitung.de",
    "dnn.de",
    "dzonline.de",
    "gea.de",
    "kn-online.de",
    "goettinger-tageblatt.de",
    "einbecker-morgenpost.de",
    "ejz.de",
    "emderzeitung.de",
    "ev-online.de",
    "esslinger-zeitung.de",
    "express.de",
    "fehmarn24.de",
    "fla.de",
    "verlag-dreisbach.de",
    "hna.de",
    "wlz-online.de",
    "frankenpost.de",
    "faz.net",
    "fr.de",
    "flz.de",
    "fnweb.de",
    "freiepresse.de",
    "fuldaerzeitung.de",
    "gandersheimer-kreisblatt.de",
    "gaeubote.de",
    "gnz.de",
    "kreis-anzeiger.de",
    "general-anzeiger-bonn.de",
    "ga-online.de",
    "giessener-anzeiger.de",
    "gifhorner-rundschau.de",
    "gmuender-tagespost.de",
    "goslarsche.de",
    "gn-online.de",
    "muensterschezeitung.de",
    "haller-kreisblatt.de",
    "halternerzeitung.de",
    "abendblatt.de",
    "mopo.de",
    "hanauer.de",
    "handelsblatt.com",
    "haz.de",
    "harzkurier.de",
    "stimme.de",
    "hellwegeranzeiger.de",
    "helmstedter-nachrichten.de",
    "hersfelder-zeitung.de",
    "hildesheimer-allgemeine.de",
    "hurriyet.com.tr",
    "ivz-aktuell.de",
    "ikz-online.de",
    "juedische-allgemeine.de",
    "kevelaerer-blatt.de",
    "ksta.de",
    "kornwestheimer-zeitung.de",
    "krzbb.de",
    "lahrer-zeitung.de",
    "lampertheimer-zeitung.de",
    "szlz.de",
    "landeszeitung.de",
    "ln-online.de",
    "lr-online.de",
    "lauterbacher-anzeiger.de",
    "leinetal24.de",
    "leonberger-kreiszeitung.de",
    "lz.de",
    "lkz.de",
    "main-spitze.de",
    "marbacher-zeitung.de",
    "verlagshaus-jaumann.de",
    "moz.de",
    "medical-tribune.de",
    "insuedthueringen.de",
    "derwesten.de",
    "milligazete.com.tr",
    "mt.de",
    "mz-web.de",
    "tag24.de",
    "muehlacker-tagblatt.de",
    "muensterlandzeitung.de",
    "om-online.de",
    "mv-online.de",
    "murrhardter-zeitung.de",
    "maerkte-weltweit.de",
    "naumburger-tageblatt.de",
    "neckar-chronik.de",
    "ndz.de",
    "neuepresse.de",
    "np-coburg.de",
    "nrz.de",
    "nordbayerischer-kurier.de",
    "nnn.de",
    "nord24.de",
    "nwzonline.de",
    "ntz.de",
    "op-marburg.de",
    "oberhessische-zeitung.de",
    "obermain.de",
    "wnoz.de",
    "rhein-zeitung.de",
    "op-online.de",
    "oz-online.de",
    "otz.de",
    "paz-online.de",
    "peiner-nachrichten.de",
    "pz-news.de",
    "pirmasenser-zeitung.de",
    "remszeitung.de",
    "rga.de",
    "tagblatt.de",
    "rheiderland.de",
    "rheingau-echo.de",
    "ruhrnachrichten.de",
    "saarbruecker-zeitung.de",
    "salzgitter-zeitung.de",
    "sn-online.de",
    "schifferstadter-tagblatt.de",
    "zvw.de",
    "schwaebische-post.de",
    "schwarzwaelder-bote.de",
    "schwarzwaelder-post.de",
    "beobachter-online.de",
    "serbske-nowiny.de",
    "siegener-zeitung.de",
    "soester-anzeiger.de",
    "solinger-tageblatt.de",
    "tageblatt.de",
    "stuttgarter-nachrichten.de",
    "stuttgarter-zeitung.de",
    "sueddeutsche.de",
    "suedkurier.de",
    "tah.de",
    "taz.de",
    "thueringer-allgemeine.de",
    "tlz.de",
    "torgauerzeitung.com",
    "traunsteiner-tagblatt.de",
    "volksfreund.de",
    "tz.de",
    "uckermarkkurier.de",
    "usinger-anzeiger.de",
    "vkz.de",
    "vdi-nachrichten.com",
    "vesti-online.com",
    "vogtland-anzeiger.de",
    "volksstimme.de",
    "wz-net.de",
    "werra-rundschau.de",
    "wz.de",
    "wp.de",
    "wr.de",
    "wa.de",
    "wetterauer-zeitung.de",
    "lokal26.de",
    "wolfenbuetteler-zeitung.de",
    "wolfsburger-nachrichten.de",
    "wormser-zeitung.de",
    "yeniozgurpolitika.net",
    "zak.de",
    "spiegel.de",
    "focus.de",
    "stern.de",
    "wiwo.de",
    "manager-magazin.de",
    "abendzeitung-muenchen.de",
    "life-und-style.info",
    "myself.de",
    "ok-magazin.de",
    "superillu.de",
    "instyle.de",
    "wunderweib.de",
    "freizeitrevue.de",
    "glamour.de",
    "faces.ch",
    # German Broadcasting
    "3sat.de",
    "arte.tv",
    "bb-mv-lokaltv.de",
    "br.de",
    "brf.de",
    "daserste.de",
    "dw.com",
    "hr-fernsehen.de",
    "kika.de",
    "mdr.de",
    "ndr.de",
    "phoenix.de",
    "radiobremen.de",
    "rbb-online.de",
    "sr.de",
    "swrfernsehen.de",
    "ard.de",
    "wdr.de",
    "zdf.de",
    "deutschlandfunk.de",
    "deutschlandfunkkultur.de",
    "deutschlandradio.de",
    "deutschlandfunknova.de",
    "hr1.de",
    "hr2.de",
    "hr3.de",
    "hr4.de",
    "you-fm.de",
    "hr-inforadio.de",
    "n-joy.de",
    "antennebrandenburg.de",
    "fritz.de",
    "inforadio.de",
    "radioeins.de",
    "unserding.de",
    "dasding.de",
    "swr3.de",
    "wdrmaus.de",
    # Swiss Mainstream Sources
    "20min.ch",
    "friday-magazine.ch",
    "24heures.ch",
    "3plus.tv",
    "4plus.tv",
    "5plus.tv",
    "6plus.tv",
    "7radio.ch",
    "smartradio.ch",
    "aargauerzeitung.ch",
    "televox.ch",
    "fcsg.ch",
    "alf-tv.ch",
    "alpenlandtv.ch",
    "alpen-welle.ch",
    "altamega.ch",
    "annabelle.ch",
    "anzeiger-luzern.ch",
    "anzeigerverband-bucheggberg-wasseramt.ch",
    "anzeigergls.ch",
    "anzeigerinterlaken.ch",
    "anzeiger-kirchberg.ch",
    "anzeigerkonolfingen.ch",
    "anzeigermichelsamt.ch",
    "azoe.ch",
    "anzeigerbern.ch",
    "anzeiger-erlach.ch",
    "anzeigertgo.ch",
    "anzeigerverbandbern.ch",
    "anzeigervomrottal.ch",
    "archebdo.ch",
    "arcmusique.ch",
    "arcinfo.ch",
    "auftanken.TV",
    "zulu-media.net",
    "badenertagblatt.ch",
    "bantigerpost.ch",
    "baernerbaer.ch",
    "bazonline.ch",
    "beautyundlife.ch",
    "beobachter.ch",
    "bernerlandbote.ch",
    "berneroberlaender.ch",
    "bestvision.tv",
    "bielbienne.com",
    "bielertagblatt.ch",
    "bilan.ch",
    "handelszeitung.ch",
    "birsfelderanzeiger.ch",
    "bibo.ch",
    "blick.ch",
    "rjb.ch",
    "boostertv.ch",
    "bote.ch",
    "wohleranzeiger.ch",
    "brunni.ch",
    "bzbasel.ch",
    "bernerzeitung.ch",
    "langenthalertagblatt.ch",
    "canal29.ch",
    "canal9.ch",
    "canalalpha.ch",
    "multivideo.ch",
    "absolutenetworks.ch",
    "channel55.tv",
    "chiassotv.ch",
    "chtv.ch",
    "mediaprofil.ch",
    "energy.ch",
    "beviacom.ch",
    "coopzeitung.ch",
    "cdt.ch",
    "CountryRadio.ch",
    "cransmontana.ch",
    "dasmagazin.ch",
    "databaar.ch",
    "derbund.ch",
    "landanzeiger.ch",
    "landbote.ch",
    "azmedien.ch",
    "unter-emmentaler.ch",
    "diaspora-tv.ch",
    "die-neue-zeit-tv.ch",
    "woz.ch",
    "dieutv.com",
    "diisradio.ch",
    "dorfblitz.ch",
    "dorfheftli.ch",
    "dregion.ch",
    "drita.tv",
    "dukascopy.tv",
    "brandsarelive.com",
    "electroradio.fm",
    "engadinerpost.ch",
    "ibexmedia.ch",
    "ewgoms.ch",
    "femina.ch",
    "sonntag.ch",
    "fuw.ch",
    "radiofm1.ch",
    "frauenfelderwoche.ch",
    "freiburger-nachrichten.ch",
    "frequencebanane.ch",
    "fridolin.ch",
    "frutiglaender.ch",
    "startv.ch",
    "gds.fm",
    "effingermedien.ch",
    "generationfm.ch",
    "genevalatina.ch",
    "ghi.ch",
    "volketswilernachrichten.ch",
    "glattwerk.ch",
    "globalfm.ch",
    "glueckspost.ch",
    "grenchnertagblatt.ch",
    "gvfm.ch",
    "hockeyfanradio.ch",
    "hockeyradio-ticino.ch",
    "hoefner.ch",
    "hoengger.ch",
    "hotelradio.fm",
    "caffe.ch",
    "illustrazione.ch",
    "tvtservices.ch",
    "ipmusic.ch",
    "jamesfm.ch",
    "journaldemorges.ch",
    "lejds.ch",
    "jump-tv.ch",
    "jungfrauzeitung.ch",
    "kanal8610.org",
    "kfn-ag.ch",
    "ktfm.ch",
    "lokalinfo.ch",
    "lacote.ch",
    "lagazette.ch",
    "la-gazette.ch",
    "lagruyere.ch",
    "laliberte.ch",
    "laregion.ch",
    "laregione.ch",
    "latele.ch",
    "ladiesdrive.tv",
    "laupenanzeiger.ch",
    "lausannecites.ch",
    "lematin.ch",
    "lemessager.ch",
    "lenouvelliste.ch",
    "lqj.ch",
    "leregional.ch",
    "letemps.ch",
    "lemanbleu.ch",
    "leutv.ch",
    "lfmtv.ch",
    "liewo.li",
    "illustre.ch",
    "limmattalerzeitung.ch",
    "informatore.net",
    "linoradio.com",
    "linthzeitung.ch",
    "btv-kreuzlingen-steckborn.ch",
    "ossingen.tv",
    "loly.ch",
    "lounge-radio.ch",
    "luzernerzeitung.ch",
    "magicradio.ch",
    "marcandcoradio.com",
    "marchanzeiger.ch",
    "maxtv.ch",
    "maxxima.org",
    "tcr-media.com",
    "migrosmagazin.ch",
    "mkd-music.tv",
    "mtv.ch",
    "murtenbieter.ch",
    "musig24.tv",
    "muttenzeranzeiger.ch",
    "mysports.ch",
    "my105.ch",
    "all3media.com",
    "nfz.ch",
    "nzz.ch",
    "nick.ch",
    "niederaemter-anzeiger.ch",
    "nrtv.ch",
    "oberaargauer.ch",
    "oberbaselbieterzeitung.ch",
    "obersee-nachrichten.ch",
    "oberwiggertaler.ch",
    "oltnertagblatt.ch",
    "onefm.ch",
    "onetv.ch",
    "onedancefm.ch",
    "openbroadcast.ch",
    "kabelfernsehen.ch",
    "ne84.ch",
    "rsi.ch",
    "rtr.ch",
    "rts.ch",
    "srf.ch",
    "swissinfo.ch",
    "puls8.ch",
    "powerup.ch",
    "premiumshopping.tv",
    "pressetv.ch",
    "prosieben.ch",
    "radio1.ch",
    "radio20coeurs.net",
    "radio24.ch",
    "radiobeo.ch",
    "radio32.ch",
    "3fach.ch",
    "r3i.ch",
    "argovia.ch",
    "basilisk.ch",
    "radiobern1.ch",
    "radio-bollwerk.ch",
    "radiobus.fm",
    "canal3.ch",
    "radiocentral.ch",
    "radiochablais.ch",
    "radiocite.ch",
    "django.fm",
    "auborddeleau.radio",
    "eviva.ch",
    "radiofr.ch",
    "radiofd.ch",
    "radiogloria.ch",
    "grrif.ch",
    "radiogwen.ch",
    "radioinside.ch",
    "kaiseregg.ch",
    "kanalk.ch",
    "lafabrik.ch",
    "radiolac.ch",
    "lfm.ch",
    "erf.ch",
    "radiololfm.ch",
    "lora.ch",
    "radio-lozâ€°rn.ch",
    "radioluzernpop.ch",
    "radiomaria.ch",
    "radiomelody.ch",
    "radiomultikulti.ch",
    "radiomunot.ch",
    "neo1.ch",
    "mitternachtsruf.ch",
    "radioonyx.org",
    "radiopilatus.ch",
    "pinkradio.com",
    "radiopositive.ch",
    "rabe.ch",
    "radioradius.ch",
    "rasa.ch",
    "rhonefm.ch",
    "rro.ch",
    "rouge.com",
    "stadtfilter.ch",
    "suedostschweiz.ch",
    "radiosummernight.ch",
    "sunshine.ch",
    "radioswissclassic.ch",
    "radioswissjazz.ch",
    "radioswisspop.ch",
    "radiotell.ch",
    "radioticino.com",
    "radiotop.ch",
    "verticalradio.ch",
    "radiovolare.com",
    "radiovostok.ch",
    "radiox.ch",
    "radio.ch",
    "radio4tng.ch",
    "radiochico.ch",
    "radio-jazz.com",
    "radiologisch.ch",
    "radioreveil.ch",
    "radiosport.ch",
    "rapbeatsradio.ch",
    "redlineradio.ch",
    "ref-gais.ch",
    "zueriost.ch",
    "regiotvplus.ch",
    "restorm.com",
    "rheinwelten.ch",
    "riehener-zeitung.ch",
    "rtvislam.com",
    "rundfunkpositiv.ch",
    "rundfunk.fm",
    "s1tv.ch",
    "sarganserlaender.ch",
    "sat1.ch",
    "bockonline.ch",
    "shf.ch",
    "shn.ch",
    "schweiz5.ch",
    "schweizamwochenende.ch",
    "schweizerfamilie.ch",
    "schweizerhockeyradio.ch",
    "schweizer-illustrierte.ch",
    "skuizz.com",
    "sowo.ch",
    "solothurnerzeitung.ch",
    "sonntagszeitung.ch",
    "radioluz.ch",
    "spoonradio.com",
    "tagblatt.ch",
    "stadtanzeiger-olten.ch",
    "stadt-anzeiger.ch",
    "deinsound.ch",
    "sunradio.ch",
    "surentaler.ch",
    "surprise.ngo",
    "swiss1.tv",
    "upstream-media.ch",
    "swissquote.ch",
    "syri.tv",
    "tagblattzuerich.ch",
    "tagesanzeiger.ch",
    "tele1.ch",
    "tele-d.ch",
    "telem1.ch",
    "tvo-online.ch",
    "toponline.ch",
    "telez.ch",
    "telebaern.ch",
    "telebasel.ch",
    "telebielingue.ch",
    "teleclub.ch",
    "telenapf.ch",
    "tele-saxon.ch",
    "teleswizz.ch",
    "teleticino.ch",
    "televersoix.ch",
    "televista.ch",
    "tep.ch",
    "tessinerzeitung.ch",
    "thuneramtsanzeiger.ch",
    "thunertagblatt.ch",
    "toxic.fm",
    "tdg.ch",
    "mynmz.ch",
    "tvoberwallis.tv",
    "tv-rheintal.ch",
    "telesuedostschweiz.ch",
    "tv24.ch",
    "tv25.ch",
    "tv4tng.ch",
    "tvm3.ch",
    "uristier.ch",
    "sevj.ch",
    "verniervisions.ch",
    "vibracionlatina.com",
    "radiovintage.ch",
    "virginradiohits.ch",
    "meteonews.ch",
    "wiggertaler.ch",
    "willisauerbote.ch",
    "wochenblatt.ch",
    "wochen-zeitung.ch",
    "zofingertagblatt.ch",
    "zugerpresse.ch",
    "zuonline.ch",
    "zsz.ch",
    # International Broadcasting
    "10tv.com",
    "6abc.com",
    "abc13.com",
    "abc15.com",
    "abc7.com",
    "abc7chicago.com",
    "abc7ny.com",
    "abcactionnews.com",
    "abcn.ws",
    "aljazeera.com",
    "antena3.com",
    "atresplayer.com",
    "bfmtv.com",
    "boston25news.com",
    "cadenaser.com",
    "canal-plus.com",
    "canal.fr",
    "cbs.com",
    "cbsloc.al",
    "cbslocal.com",
    "cbsn.ws",
    "cbsnews.com",
    "channel7breakingreport.live",
    "cnbc.com",
    "cnn.com",
    "cnn.it",
    "cope.es",
    "cuatro.com",
    "europe1.fr",
    "firstcoastnews.com",
    "fox.com",
    "fox13news.com",
    "fox13now.com",
    "fox2now.com",
    "fox4kc.com",
    "fox59.com",
    "fox6now.com",
    "fox8.com",
    "fox9.com",
    "foxbusiness.com",
    "foxla.com",
    "foxnews.com",
    "globo.com",
    "goodmorningamerica.com",
    "insideedition.com",
    "itv.com",
    "komonews.com",
    "lasexta.com",
    "lbc.co.uk",
    "local10.com",
    "local12.com",
    "mediaset.it",
    "msnbc.com",
    "nbc.com",
    "nbcchicago.com",
    "nbcdfw.com",
    "nbclosangeles.com",
    "nbcnews.com",
    "nbcnews.to",
    "nbcnewyork.com",
    "ndtv.com",
    "news12.com",
    "news4jax.com",
    "news5cleveland.com",
    "ondacero.es",
    "primocanale.it",
    "prosieben.at",
    "rac1.cat",
    "radioclassique.fr",
    "radioitalia.it",
    "rtl.fr",
    "sky.com",
    "sky.it",
    "skytg24news.it",
    "telecinco.es",
    "telemundo.com",
    "tf1.fr",
    "tgcom24.it",
    "weau.com",
    "wpxi.com",
    "wsbtv.com",
    "wxyz.com",
    # International News Websites
    "24economia.com",
    "affaritaliani.it",
    "agoravox.fr",
    "arcamax.com",
    "bento.de",
    "blitzquotidiano.it",
    "breaknotizie.com",
    "businessinsider.com",
    "businessinsider.de",
    "buzzfeed.com",
    "buzzfeednews.com",
    "caffeinamagazine.it",
    "cnews.fr",
    "ctxt.es",
    "economiadigital.es",
    "elboletin.com",
    "elconfidencial.com",
    "elconfidencialdigital.com",
    "eldiario.es",
    "eldigitalcastillalamancha.es",
    "elespanol.com",
    "estrelladigital.es",
    "fanpage.it",
    "finanzen.net",
    "fivethirtyeight.com",
    "francesoir.fr",
    "gasteizhoy.com",
    "huffingtonpost.co.uk",
    "huffingtonpost.com",
    "huffingtonpost.es",
    "huffingtonpost.fr",
    "huffingtonpost.it",
    "huffpost.com",
    "infolibre.es",
    "kentonline.co.uk",
    "lainformacion.com",
    "lapresse.it",
    "lavozdelsur.es",
    "leggioggi.it",
    "lettoquotidiano.it",
    "libertaddigital.com",
    "linternaute.com",
    "linternaute.fr",
    "livenewsnow.com",
    "livesicilia.it",
    "mediapart.fr",
    "naciodigital.cat",
    "news-mondo.it",
    "news-und-nachrichten.de",
    "news.com.au",
    "news.de",
    "news64.net",
    "newsbreakapp.com",
    "newser.com",
    "newsmondo.it",
    "newsnow.co.uk",
    "nextquotidiano.it",
    "noticias24.com",
    "notizie.it",
    "politico.com",
    "presseportal.de",
    "publico.es",
    "quifinanza.it",
    "quotidianodiragusa.it",
    "quotidianopiemontese.it",
    "regio7.cat",
    "repubblica.it",
    "republicain-lorrain.fr",
    "reuters.com",
    "riminitoday.it",
    "romatoday.it",
    "seattletimes.com",
    "sfgate.com",
    "startribune.com",
    "sudinfo.be",
    "sudouest.fr",
    "sun-sentinel.com",
    "telegraph.co.uk",
    "theatlantic.com",
    "theguardian.com",
    "thehill.com",
    "thetelegraphandargus.co.uk",
    "thetimes.co.uk",
    "time.com",
    "torinotoday.it",
    "trevisotoday.it",
    "udinetoday.it",
    "usnews.com",
    "valeursactuelles.com",
    "washingtonexaminer.com",
    "washingtonpost.com",
    "washingtontimes.com",
    "waz.de",
    "wired.com",
    "wsj.com",
    "20minutes.fr",
    "20minutos.es",
    "20mn.fr",
    "blick.de",
    "dailymail.co.uk",
    "dailyrecord.co.uk",
    "dailystar.co.uk",
    "eveningtimes.co.uk",
    "express.co.uk",
    "hulldailymail.co.uk",
    "ilrestodelcarlino.it",
    "journaldemontreal.com",
    "lanazione.it",
    "leggo.it",
    "leparisien.fr",
    "metro.co.uk",
    "metro.it",
    "mirror.co.uk",
    "nydailynews.com",
    "nypost.com",
    "parismatch.com",
    "que.es",
    "standard.co.uk",
    "suntimes.com",
    "thesun.co.uk",
    "trinitymirror-news.co.uk",
    "usatoday.com",
    "infosperber.ch",
]

# =============================================================================
# CORE FUNCTIONS
# =============================================================================


def extract_domain(url: str) -> str:
    """Extract the domain from a URL."""
    try:
        parsed = urlparse(url)
        # Remove 'www.' if present
        domain = re.sub(r"^www\.", "", parsed.netloc.lower())
        return domain
    except:
        return None


def classify_news_source(domain: str) -> str:
    """Classify a domain as alternative, mainstream, or other."""
    if domain is None:
        return "invalid_url"

    # Check alternative news sources - use exact domain matching
    if domain in alternative_news_sources:
        return "alternative"

    # Check mainstream news sources - use exact domain matching
    if domain in mainstream_news_sources:
        return "mainstream"

    return "other"


def analyze_news_sources(df: pd.DataFrame) -> Dict[str, Any]:
    """Analyze news sources in the DataFrame."""
    # Extract domains from URLs
    domains = df["url"].apply(extract_domain)

    # Classify each domain
    classifications = domains.apply(classify_news_source)

    # Count occurrences of each domain
    domain_counts = Counter(domains.dropna())

    # Count classifications
    classification_counts = Counter(classifications)

    # Get top domains for each category
    alternative_domains = {
        domain: count
        for domain, count in domain_counts.items()
        if classify_news_source(domain) == "alternative"
    }
    mainstream_domains = {
        domain: count
        for domain, count in domain_counts.items()
        if classify_news_source(domain) == "mainstream"
    }

    return {
        "classification_summary": dict(classification_counts),
        "alternative_sources": dict(
            sorted(alternative_domains.items(), key=lambda x: x[1], reverse=True)
        ),
        "mainstream_sources": dict(
            sorted(mainstream_domains.items(), key=lambda x: x[1], reverse=True)
        ),
    }


def save_analysis_results(
    results: Dict[str, Any], output_dir: str = "../data/processed/"
):
    """Save analysis results to CSV and Excel files."""
    # Create timestamp for unique filenames
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Convert results to DataFrames
    # Summary DataFrame
    summary_df = pd.DataFrame([results["classification_summary"]]).T
    summary_df.columns = ["count"]
    summary_df.index.name = "category"

    # Alternative sources DataFrame
    alt_df = pd.DataFrame.from_dict(
        results["alternative_sources"], orient="index", columns=["visits"]
    )
    alt_df.index.name = "domain"

    # Mainstream sources DataFrame
    main_df = pd.DataFrame.from_dict(
        results["mainstream_sources"], orient="index", columns=["visits"]
    )
    main_df.index.name = "domain"

    # Save to CSV
    summary_df.to_csv(f"{output_dir}news_classification_summary_{timestamp}.csv")
    alt_df.to_csv(f"{output_dir}alternative_news_sources_{timestamp}.csv")
    main_df.to_csv(f"{output_dir}mainstream_news_sources_{timestamp}.csv")

    # Save to Excel (all in one file with different sheets)
    with pd.ExcelWriter(
        f"{output_dir}news_sources_analysis_{timestamp}.xlsx"
    ) as writer:
        summary_df.to_excel(writer, sheet_name="Summary")
        alt_df.to_excel(writer, sheet_name="Alternative_Sources")
        main_df.to_excel(writer, sheet_name="Mainstream_Sources")

    print(f"Analysis results saved to {output_dir}")
    print(f"Files created:")
    print(f"  - news_classification_summary_{timestamp}.csv")
    print(f"  - alternative_news_sources_{timestamp}.csv")
    print(f"  - mainstream_news_sources_{timestamp}.csv")
    print(f"  - news_sources_analysis_{timestamp}.xlsx")


# =============================================================================
# FACEBOOK-SPECIFIC FUNCTIONS
# =============================================================================


def analyze_facebook_directory(
    base_dir: str, output_dir: str = "../data/processed/"
) -> Dict[str, Any]:
    """Analyze Facebook data directory for news sources."""
    print(f"Analyzing Facebook directory: {base_dir}")

    # This function would contain the Facebook-specific analysis logic
    # For now, we'll provide a placeholder that can be expanded

    results = {
        "classification_summary": {"alternative": 0, "mainstream": 0, "other": 0},
        "alternative_sources": {},
        "mainstream_sources": {},
    }

    return results


# =============================================================================
# MAIN FUNCTION
# =============================================================================


def main():
    """Main function for standalone execution."""
    import argparse

    parser = argparse.ArgumentParser(description="News Source Analysis")
    parser.add_argument("--input", "-i", required=True, help="Input CSV file with URLs")
    parser.add_argument(
        "--output", "-o", default="../data/processed/", help="Output directory"
    )
    parser.add_argument("--facebook", action="store_true", help="Analyze Facebook data")

    args = parser.parse_args()

    if args.facebook:
        # Facebook analysis
        results = analyze_facebook_directory(args.input, args.output)
    else:
        # Standard analysis
        df = pd.read_csv(args.input)
        results = analyze_news_sources(df)

    save_analysis_results(results, args.output)

    print("\nAnalysis complete!")
    print(f"Summary: {results['classification_summary']}")


if __name__ == "__main__":
    main()
